filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log
  ignore_older: 0
  start_position: beginning

logging.level: debug


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true


processors:
- add_docker_metadata: ~


setup.kibana:
  host: ${KIBANA_HOSTS}
  username: elastic
  password: ${ELASTIC_PASSWORD}


output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"